version: '3.8'
services:
  app:
    build: .
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8000:80"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Sanjayreddy125$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Sanjayreddy125$", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
